### ISSUE TITLE
[feature request] SLO AWS CloudWatch support

### ISSUE THREAD

**Issue by FelixBarsnickTS** [nobl9/terraform-provider-nobl9#28]
Dear Nobl9 team,

would it be possible to soon add AWS Cloudwatch support to the nobl9_slo resource?
That would save us many many yaml files and make managing SLOs a lot easier and efficient.

Best, Felix

**Comment by kskitek** [comment]
Hi Felix,

Thanks for letting us know about your requirement.
We have started working on support for Cloudwatch - I will let you know when it's ready.

**Comment by davex98** [comment]
Hi Felix,

We have just released a new version of our terraform provider that supports CloudWatch - v.0.3.0. 🚀 
It is available [here](https://registry.terraform.io/providers/nobl9/nobl9/latest).

Best, Jakub
