### ISSUE TITLE
SLOs set labels

### ISSUE THREAD

**Issue by FelixBarsnickTS** [nobl9/terraform-provider-nobl9#33]
Hi Nobl9 team,

I am currently building SLOs transitioning from yaml to terraform.
Is it possible to set (multiple) labels for SLOs or is it just missing in the documentation?

Thanks for your help
Felix

**Comment by kskitek** [comment]
Hi Felix,

Labels are currently not supported in our terraform provider.
It is already identified as a missing feature - I will bring your request to our product team.
Thanks for letting us know about your needs - this helps us prioritizing :)

**Comment by FelixBarsnickTS** [comment]
Hi @NataliaSikora end of the month sounds very good, thank you very much for the reply

**Comment by kskitek** [comment]
Hey, @FelixBarsnickTS we are starting the work on labels support. I will let you know next week when it will be ready.

**Comment by kskitek** [comment]
Hi @FelixBarsnickTS, we plan to release labels support next week.

**Comment by FelixBarsnickTS** [comment]
Hello, is there an update when this feature could be released?

**Comment by NataliaSikora** [comment]
Hi Felix, Apologies for the delay. This task is currently in review, waiting for the next release slot scheduled within 1-2 weeks.

**Comment by ptak7** [comment]
Hi @FelixBarsnickTS , we added label support in [v0.5.0](https://registry.terraform.io/providers/nobl9/nobl9/0.5.0)
You can see the docs and examples how to use them [here](https://registry.terraform.io/providers/nobl9/nobl9/latest/docs/resources/slo)
```
  label {
    key    = "env"
    values = ["dev", "prod"]
  }

  label {
    key    = "team"
    values = ["red"]
  }
```

**Comment by ptak7** [comment]
Fixed in https://github.com/nobl9/terraform-provider-nobl9/pull/45
