### ISSUE TITLE
SLO impossible to delete alert_policies

### ISSUE THREAD

**Issue by FelixBarsnickTS** [nobl9/terraform-provider-nobl9#40]
Hi Nobl9 team,

I am currently building SLOs transitioning from yaml to terraform.
When I deploy SLOs with an alert policy set and then try to remove it with alert_policies = null nothing happens.
The cli output of terraform just says No Changes and nothing to do. According to the documentation and also the web ui alert policies in SLOs are optional and it should be possible to be removed.

Thanks for your help
Felix

**Comment by kskitek** [comment]
Sounds like a bug. We will investigate it and let you know.

**Comment by klaudia-nobl9** [comment]
HI @FelixBarsnickTS we can confirm it's a bug. For now, you can use the workaround: `alert_policies = []` and we will deal with this null bug in future releases.

**Comment by FelixBarsnickTS** [comment]
Hi @klaudia-nobl9 thanks for getting back. Is there an estimate when a fix could be released?

**Comment by kskitek** [comment]
Right now we are working on labels support, issues #41 and #40 are next in the line.

**Comment by FelixBarsnickTS** [comment]
@kskitek Sounds good. Regarding priorities labels would be most important, #41 next and #40 last
