### ISSUE TITLE
SLO time_windows always redeployed period with is_rolling = true

### ISSUE THREAD

**Issue by FelixBarsnickTS** [nobl9/terraform-provider-nobl9#41]
Hi Nobl9 team,

I am currently building SLOs transitioning from yaml to terraform.
I set the time_window to a rolling 14 day window.

time_window {
  unit       = "Day"
  count      = 14
  is_rolling = true
}

When I deploy it and run terraform apply afterwards the time_window is always again redeployed with new period values. As the window is rolling that does not make sense and is just confusing as nothing changed in the code and the period is handled serverside.

![image](https://user-images.githubusercontent.com/92578573/181483927-8f316858-ee94-4645-8bcb-e2afbf4f97cd.png)

Thanks for your help
Felix

**Comment by kskitek** [comment]
I think I have seen this one in the past.. We will take care of that.

**Comment by FelixBarsnickTS** [comment]
Issue is no longer happening in provider v 0.6.0
